// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/agent.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricType int32

const (
	MetricType_GAUGE     MetricType = 0
	MetricType_COUNTER   MetricType = 1
	MetricType_HISTOGRAM MetricType = 2
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "GAUGE",
		1: "COUNTER",
		2: "HISTOGRAM",
	}
	MetricType_value = map[string]int32{
		"GAUGE":     0,
		"COUNTER":   1,
		"HISTOGRAM": 2,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Registration
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Metrics
	//	*AgentMessage_ExecOutput
	//	*AgentMessage_ExecResult
	//	*AgentMessage_Ack
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegistration() *AgentRegistration {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetMetrics() *MetricBatch {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *AgentMessage) GetExecOutput() *ExecOutput {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ExecOutput); ok {
			return x.ExecOutput
		}
	}
	return nil
}

func (x *AgentMessage) GetExecResult() *ExecResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ExecResult); ok {
			return x.ExecResult
		}
	}
	return nil
}

func (x *AgentMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Registration struct {
	Registration *AgentRegistration `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Metrics struct {
	Metrics *MetricBatch `protobuf:"bytes,3,opt,name=metrics,proto3,oneof"`
}

type AgentMessage_ExecOutput struct {
	ExecOutput *ExecOutput `protobuf:"bytes,4,opt,name=exec_output,json=execOutput,proto3,oneof"`
}

type AgentMessage_ExecResult struct {
	ExecResult *ExecResult `protobuf:"bytes,5,opt,name=exec_result,json=execResult,proto3,oneof"`
}

type AgentMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,6,opt,name=ack,proto3,oneof"`
}

func (*AgentMessage_Registration) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_Metrics) isAgentMessage_Payload() {}

func (*AgentMessage_ExecOutput) isAgentMessage_Payload() {}

func (*AgentMessage_ExecResult) isAgentMessage_Payload() {}

func (*AgentMessage_Ack) isAgentMessage_Payload() {}

type PlatformMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PlatformMessage_ExecCommand
	//	*PlatformMessage_ExecScript
	//	*PlatformMessage_CancelJob
	//	*PlatformMessage_ConfigUpdate
	//	*PlatformMessage_Ack
	Payload       isPlatformMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformMessage) Reset() {
	*x = PlatformMessage{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformMessage) ProtoMessage() {}

func (x *PlatformMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformMessage.ProtoReflect.Descriptor instead.
func (*PlatformMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PlatformMessage) GetPayload() isPlatformMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PlatformMessage) GetExecCommand() *ExecuteCommand {
	if x != nil {
		if x, ok := x.Payload.(*PlatformMessage_ExecCommand); ok {
			return x.ExecCommand
		}
	}
	return nil
}

func (x *PlatformMessage) GetExecScript() *ExecuteScript {
	if x != nil {
		if x, ok := x.Payload.(*PlatformMessage_ExecScript); ok {
			return x.ExecScript
		}
	}
	return nil
}

func (x *PlatformMessage) GetCancelJob() *CancelJob {
	if x != nil {
		if x, ok := x.Payload.(*PlatformMessage_CancelJob); ok {
			return x.CancelJob
		}
	}
	return nil
}

func (x *PlatformMessage) GetConfigUpdate() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Payload.(*PlatformMessage_ConfigUpdate); ok {
			return x.ConfigUpdate
		}
	}
	return nil
}

func (x *PlatformMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*PlatformMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isPlatformMessage_Payload interface {
	isPlatformMessage_Payload()
}

type PlatformMessage_ExecCommand struct {
	ExecCommand *ExecuteCommand `protobuf:"bytes,1,opt,name=exec_command,json=execCommand,proto3,oneof"`
}

type PlatformMessage_ExecScript struct {
	ExecScript *ExecuteScript `protobuf:"bytes,2,opt,name=exec_script,json=execScript,proto3,oneof"`
}

type PlatformMessage_CancelJob struct {
	CancelJob *CancelJob `protobuf:"bytes,3,opt,name=cancel_job,json=cancelJob,proto3,oneof"`
}

type PlatformMessage_ConfigUpdate struct {
	ConfigUpdate *ConfigUpdate `protobuf:"bytes,4,opt,name=config_update,json=configUpdate,proto3,oneof"`
}

type PlatformMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,5,opt,name=ack,proto3,oneof"`
}

func (*PlatformMessage_ExecCommand) isPlatformMessage_Payload() {}

func (*PlatformMessage_ExecScript) isPlatformMessage_Payload() {}

func (*PlatformMessage_CancelJob) isPlatformMessage_Payload() {}

func (*PlatformMessage_ConfigUpdate) isPlatformMessage_Payload() {}

func (*PlatformMessage_Ack) isPlatformMessage_Payload() {}

type AgentRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	AgentInfo     *AgentInfo             `protobuf:"bytes,3,opt,name=agent_info,json=agentInfo,proto3" json:"agent_info,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegistration) Reset() {
	*x = AgentRegistration{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegistration) ProtoMessage() {}

func (x *AgentRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegistration.ProtoReflect.Descriptor instead.
func (*AgentRegistration) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentRegistration) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentRegistration) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AgentRegistration) GetAgentInfo() *AgentInfo {
	if x != nil {
		return x.AgentInfo
	}
	return nil
}

func (x *AgentRegistration) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	CpuCores      int32                  `protobuf:"varint,5,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,6,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	RunningTasks  int32                  `protobuf:"varint,7,opt,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	MaxTasks      int32                  `protobuf:"varint,8,opt,name=max_tasks,json=maxTasks,proto3" json:"max_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *AgentInfo) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *AgentInfo) GetRunningTasks() int32 {
	if x != nil {
		return x.RunningTasks
	}
	return 0
}

func (x *AgentInfo) GetMaxTasks() int32 {
	if x != nil {
		return x.MaxTasks
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	AgentInfo     *AgentInfo             `protobuf:"bytes,4,opt,name=agent_info,json=agentInfo,proto3" json:"agent_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Heartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Heartbeat) GetAgentInfo() *AgentInfo {
	if x != nil {
		return x.AgentInfo
	}
	return nil
}

type MetricBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricBatch) Reset() {
	*x = MetricBatch{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBatch) ProtoMessage() {}

func (x *MetricBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBatch.ProtoReflect.Descriptor instead.
func (*MetricBatch) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *MetricBatch) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Fields        []*Field               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Type          MetricType             `protobuf:"varint,5,opt,name=type,proto3,enum=github.com/cy77cc/nodeagentx.MetricType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Metric) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Metric) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Metric) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_GAUGE
}

type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Field_DoubleValue
	//	*Field_IntValue
	//	*Field_StringValue
	//	*Field_BoolValue
	Value         isField_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Field) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Field) GetValue() isField_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Field) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Field_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Field) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Field_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Field) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Field_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Field) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Field_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isField_Value interface {
	isField_Value()
}

type Field_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Field_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Field_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Field_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*Field_DoubleValue) isField_Value() {}

func (*Field_IntValue) isField_Value() {}

func (*Field_StringValue) isField_Value() {}

func (*Field_BoolValue) isField_Value() {}

type ExecuteCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args           []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Sandbox        *SandboxConfig         `protobuf:"bytes,6,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteCommand) Reset() {
	*x = ExecuteCommand{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommand) ProtoMessage() {}

func (x *ExecuteCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommand.ProtoReflect.Descriptor instead.
func (*ExecuteCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteCommand) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteCommand) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteCommand) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteCommand) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecuteCommand) GetSandbox() *SandboxConfig {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type ExecuteScript struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Interpreter    string                 `protobuf:"bytes,2,opt,name=interpreter,proto3" json:"interpreter,omitempty"`
	Script         string                 `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`
	Args           []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Env            map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Sandbox        *SandboxConfig         `protobuf:"bytes,7,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteScript) Reset() {
	*x = ExecuteScript{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteScript) ProtoMessage() {}

func (x *ExecuteScript) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteScript.ProtoReflect.Descriptor instead.
func (*ExecuteScript) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteScript) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteScript) GetInterpreter() string {
	if x != nil {
		return x.Interpreter
	}
	return ""
}

func (x *ExecuteScript) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *ExecuteScript) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteScript) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteScript) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecuteScript) GetSandbox() *SandboxConfig {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type SandboxConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryMb      int32                  `protobuf:"varint,1,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	CpuQuotaPct   int32                  `protobuf:"varint,2,opt,name=cpu_quota_pct,json=cpuQuotaPct,proto3" json:"cpu_quota_pct,omitempty"`
	MaxPids       int32                  `protobuf:"varint,3,opt,name=max_pids,json=maxPids,proto3" json:"max_pids,omitempty"`
	NetworkMode   string                 `protobuf:"bytes,4,opt,name=network_mode,json=networkMode,proto3" json:"network_mode,omitempty"`
	AllowedIps    []string               `protobuf:"bytes,5,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	MaxOutputKb   int32                  `protobuf:"varint,6,opt,name=max_output_kb,json=maxOutputKb,proto3" json:"max_output_kb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxConfig) Reset() {
	*x = SandboxConfig{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxConfig) ProtoMessage() {}

func (x *SandboxConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxConfig.ProtoReflect.Descriptor instead.
func (*SandboxConfig) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *SandboxConfig) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *SandboxConfig) GetCpuQuotaPct() int32 {
	if x != nil {
		return x.CpuQuotaPct
	}
	return 0
}

func (x *SandboxConfig) GetMaxPids() int32 {
	if x != nil {
		return x.MaxPids
	}
	return 0
}

func (x *SandboxConfig) GetNetworkMode() string {
	if x != nil {
		return x.NetworkMode
	}
	return ""
}

func (x *SandboxConfig) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *SandboxConfig) GetMaxOutputKb() int32 {
	if x != nil {
		return x.MaxOutputKb
	}
	return 0
}

type ExecOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOutput) Reset() {
	*x = ExecOutput{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOutput) ProtoMessage() {}

func (x *ExecOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOutput.ProtoReflect.Descriptor instead.
func (*ExecOutput) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ExecOutput) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecOutput) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *ExecOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecOutput) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type ExecResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	TimedOut      bool                   `protobuf:"varint,4,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	Truncated     bool                   `protobuf:"varint,5,opt,name=truncated,proto3" json:"truncated,omitempty"`
	Killed        bool                   `protobuf:"varint,6,opt,name=killed,proto3" json:"killed,omitempty"`
	Stats         *ExecStats             `protobuf:"bytes,7,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResult) Reset() {
	*x = ExecResult{}
	mi := &file_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResult) ProtoMessage() {}

func (x *ExecResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResult.ProtoReflect.Descriptor instead.
func (*ExecResult) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ExecResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ExecResult) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *ExecResult) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *ExecResult) GetKilled() bool {
	if x != nil {
		return x.Killed
	}
	return false
}

func (x *ExecResult) GetStats() *ExecStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ExecStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeakMemoryBytes int64                  `protobuf:"varint,1,opt,name=peak_memory_bytes,json=peakMemoryBytes,proto3" json:"peak_memory_bytes,omitempty"`
	CpuTimeUserMs   int64                  `protobuf:"varint,2,opt,name=cpu_time_user_ms,json=cpuTimeUserMs,proto3" json:"cpu_time_user_ms,omitempty"`
	CpuTimeSystemMs int64                  `protobuf:"varint,3,opt,name=cpu_time_system_ms,json=cpuTimeSystemMs,proto3" json:"cpu_time_system_ms,omitempty"`
	ProcessCount    int32                  `protobuf:"varint,4,opt,name=process_count,json=processCount,proto3" json:"process_count,omitempty"`
	BytesWritten    int64                  `protobuf:"varint,5,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	BytesRead       int64                  `protobuf:"varint,6,opt,name=bytes_read,json=bytesRead,proto3" json:"bytes_read,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecStats) Reset() {
	*x = ExecStats{}
	mi := &file_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStats) ProtoMessage() {}

func (x *ExecStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStats.ProtoReflect.Descriptor instead.
func (*ExecStats) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ExecStats) GetPeakMemoryBytes() int64 {
	if x != nil {
		return x.PeakMemoryBytes
	}
	return 0
}

func (x *ExecStats) GetCpuTimeUserMs() int64 {
	if x != nil {
		return x.CpuTimeUserMs
	}
	return 0
}

func (x *ExecStats) GetCpuTimeSystemMs() int64 {
	if x != nil {
		return x.CpuTimeSystemMs
	}
	return 0
}

func (x *ExecStats) GetProcessCount() int32 {
	if x != nil {
		return x.ProcessCount
	}
	return 0
}

func (x *ExecStats) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *ExecStats) GetBytesRead() int64 {
	if x != nil {
		return x.BytesRead
	}
	return 0
}

type CancelJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJob) Reset() {
	*x = CancelJob{}
	mi := &file_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJob) ProtoMessage() {}

func (x *CancelJob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJob.ProtoReflect.Descriptor instead.
func (*CancelJob) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *CancelJob) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelJob) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigYaml    []byte                 `protobuf:"bytes,1,opt,name=config_yaml,json=configYaml,proto3" json:"config_yaml,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigUpdate) GetConfigYaml() []byte {
	if x != nil {
		return x.ConfigYaml
	}
	return nil
}

func (x *ConfigUpdate) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefId         string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *Ack) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\n" +
	"github.com/cy77cc/nodeagentx\"\xe5\x02\n" +
	"\fAgentMessage\x12C\n" +
	"\fregistration\x18\x01 \x01(\v2\x1d.github.com/cy77cc/nodeagentx.AgentRegistrationH\x00R\fregistration\x125\n" +
	"\theartbeat\x18\x02 \x01(\v2\x15.github.com/cy77cc/nodeagentx.HeartbeatH\x00R\theartbeat\x123\n" +
	"\ametrics\x18\x03 \x01(\v2\x17.github.com/cy77cc/nodeagentx.MetricBatchH\x00R\ametrics\x129\n" +
	"\vexec_output\x18\x04 \x01(\v2\x16.github.com/cy77cc/nodeagentx.ExecOutputH\x00R\n" +
	"execOutput\x129\n" +
	"\vexec_result\x18\x05 \x01(\v2\x16.github.com/cy77cc/nodeagentx.ExecResultH\x00R\n" +
	"execResult\x12#\n" +
	"\x03ack\x18\x06 \x01(\v2\x0f.github.com/cy77cc/nodeagentx.AckH\x00R\x03ackB\t\n" +
	"\apayload\"\xb9\x02\n" +
	"\x0fPlatformMessage\x12?\n" +
	"\fexec_command\x18\x01 \x01(\v2\x1a.github.com/cy77cc/nodeagentx.ExecuteCommandH\x00R\vexecCommand\x12<\n" +
	"\vexec_script\x18\x02 \x01(\v2\x19.github.com/cy77cc/nodeagentx.ExecuteScriptH\x00R\n" +
	"execScript\x126\n" +
	"\n" +
	"cancel_job\x18\x03 \x01(\v2\x15.github.com/cy77cc/nodeagentx.CancelJobH\x00R\tcancelJob\x12?\n" +
	"\rconfig_update\x18\x04 \x01(\v2\x18.github.com/cy77cc/nodeagentx.ConfigUpdateH\x00R\fconfigUpdate\x12#\n" +
	"\x03ack\x18\x05 \x01(\v2\x0f.github.com/cy77cc/nodeagentx.AckH\x00R\x03ackB\t\n" +
	"\apayload\"\x9e\x01\n" +
	"\x11AgentRegistration\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x124\n" +
	"\n" +
	"agent_info\x18\x03 \x01(\v2\x15.github.com/cy77cc/nodeagentx.AgentInfoR\tagentInfo\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"\xe7\x01\n" +
	"\tAgentInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1b\n" +
	"\tcpu_cores\x18\x05 \x01(\x05R\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\x06 \x01(\x03R\vmemoryBytes\x12#\n" +
	"\rrunning_tasks\x18\a \x01(\x05R\frunningTasks\x12\x1b\n" +
	"\tmax_tasks\x18\b \x01(\x05R\bmaxTasks\"\x97\x01\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x124\n" +
	"\n" +
	"agent_info\x18\x04 \x01(\v2\x15.github.com/cy77cc/nodeagentx.AgentInfoR\tagentInfo\";\n" +
	"\vMetricBatch\x12,\n" +
	"\ametrics\x18\x01 \x03(\v2\x12.github.com/cy77cc/nodeagentx.MetricR\ametrics\"\x81\x02\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x04tags\x18\x02 \x03(\v2\x1c.github.com/cy77cc/nodeagentx.Metric.TagsEntryR\x04tags\x12)\n" +
	"\x06fields\x18\x03 \x03(\v2\x11.github.com/cy77cc/nodeagentx.FieldR\x06fields\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\x12*\n" +
	"\x04type\x18\x05 \x01(\x0e2\x16.github.com/cy77cc/nodeagentx.MetricTypeR\x04type\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\x05Field\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\fdouble_value\x18\x02 \x01(\x01H\x00R\vdoubleValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fstring_value\x18\x04 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x05 \x01(\bH\x00R\tboolValueB\a\n" +
	"\x05value\"\xa4\x02\n" +
	"\x0eExecuteCommand\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x125\n" +
	"\x03env\x18\x04 \x03(\v2#.github.com/cy77cc/nodeagentx.ExecuteCommand.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x123\n" +
	"\asandbox\x18\x06 \x01(\v2\x19.github.com/cy77cc/nodeagentx.SandboxConfigR\asandbox\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x02\n" +
	"\rExecuteScript\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12 \n" +
	"\vinterpreter\x18\x02 \x01(\tR\vinterpreter\x12\x16\n" +
	"\x06script\x18\x03 \x01(\tR\x06script\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x124\n" +
	"\x03env\x18\x05 \x03(\v2\".github.com/cy77cc/nodeagentx.ExecuteScript.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\x123\n" +
	"\asandbox\x18\a \x01(\v2\x19.github.com/cy77cc/nodeagentx.SandboxConfigR\asandbox\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd3\x01\n" +
	"\rSandboxConfig\x12\x1b\n" +
	"\tmemory_mb\x18\x01 \x01(\x05R\bmemoryMb\x12\"\n" +
	"\rcpu_quota_pct\x18\x02 \x01(\x05R\vcpuQuotaPct\x12\x19\n" +
	"\bmax_pids\x18\x03 \x01(\x05R\amaxPids\x12!\n" +
	"\fnetwork_mode\x18\x04 \x01(\tR\vnetworkMode\x12\x1f\n" +
	"\vallowed_ips\x18\x05 \x03(\tR\n" +
	"allowedIps\x12\"\n" +
	"\rmax_output_kb\x18\x06 \x01(\x05R\vmaxOutputKb\"t\n" +
	"\n" +
	"ExecOutput\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\"\xe3\x01\n" +
	"\n" +
	"ExecResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12\x1b\n" +
	"\ttimed_out\x18\x04 \x01(\bR\btimedOut\x12\x1c\n" +
	"\ttruncated\x18\x05 \x01(\bR\ttruncated\x12\x16\n" +
	"\x06killed\x18\x06 \x01(\bR\x06killed\x12+\n" +
	"\x05stats\x18\a \x01(\v2\x15.github.com/cy77cc/nodeagentx.ExecStatsR\x05stats\"\xf6\x01\n" +
	"\tExecStats\x12*\n" +
	"\x11peak_memory_bytes\x18\x01 \x01(\x03R\x0fpeakMemoryBytes\x12'\n" +
	"\x10cpu_time_user_ms\x18\x02 \x01(\x03R\rcpuTimeUserMs\x12+\n" +
	"\x12cpu_time_system_ms\x18\x03 \x01(\x03R\x0fcpuTimeSystemMs\x12#\n" +
	"\rprocess_count\x18\x04 \x01(\x05R\fprocessCount\x12#\n" +
	"\rbytes_written\x18\x05 \x01(\x03R\fbytesWritten\x12\x1d\n" +
	"\n" +
	"bytes_read\x18\x06 \x01(\x03R\tbytesRead\"<\n" +
	"\tCancelJob\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"I\n" +
	"\fConfigUpdate\x12\x1f\n" +
	"\vconfig_yaml\x18\x01 \x01(\fR\n" +
	"configYaml\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"L\n" +
	"\x03Ack\x12\x15\n" +
	"\x06ref_id\x18\x01 \x01(\tR\x05refId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*3\n" +
	"\n" +
	"MetricType\x12\t\n" +
	"\x05GAUGE\x10\x00\x12\v\n" +
	"\aCOUNTER\x10\x01\x12\r\n" +
	"\tHISTOGRAM\x10\x022T\n" +
	"\fAgentService\x12D\n" +
	"\aConnect\x12\x18.github.com/cy77cc/nodeagentx.AgentMessage\x1a\x1b.github.com/cy77cc/nodeagentx.PlatformMessage(\x010\x01B&Z$github.com/cy77cc/nodeagentx/internal/grpcclient/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_agent_proto_goTypes = []any{
	(MetricType)(0),           // 0: github.com/cy77cc/nodeagentx.MetricType
	(*AgentMessage)(nil),      // 1: github.com/cy77cc/nodeagentx.AgentMessage
	(*PlatformMessage)(nil),   // 2: github.com/cy77cc/nodeagentx.PlatformMessage
	(*AgentRegistration)(nil), // 3: github.com/cy77cc/nodeagentx.AgentRegistration
	(*AgentInfo)(nil),         // 4: github.com/cy77cc/nodeagentx.AgentInfo
	(*Heartbeat)(nil),         // 5: github.com/cy77cc/nodeagentx.Heartbeat
	(*MetricBatch)(nil),       // 6: github.com/cy77cc/nodeagentx.MetricBatch
	(*Metric)(nil),            // 7: github.com/cy77cc/nodeagentx.Metric
	(*Field)(nil),             // 8: github.com/cy77cc/nodeagentx.Field
	(*ExecuteCommand)(nil),    // 9: github.com/cy77cc/nodeagentx.ExecuteCommand
	(*ExecuteScript)(nil),     // 10: github.com/cy77cc/nodeagentx.ExecuteScript
	(*SandboxConfig)(nil),     // 11: github.com/cy77cc/nodeagentx.SandboxConfig
	(*ExecOutput)(nil),        // 12: github.com/cy77cc/nodeagentx.ExecOutput
	(*ExecResult)(nil),        // 13: github.com/cy77cc/nodeagentx.ExecResult
	(*ExecStats)(nil),         // 14: github.com/cy77cc/nodeagentx.ExecStats
	(*CancelJob)(nil),         // 15: github.com/cy77cc/nodeagentx.CancelJob
	(*ConfigUpdate)(nil),      // 16: github.com/cy77cc/nodeagentx.ConfigUpdate
	(*Ack)(nil),               // 17: github.com/cy77cc/nodeagentx.Ack
	nil,                       // 18: github.com/cy77cc/nodeagentx.Metric.TagsEntry
	nil,                       // 19: github.com/cy77cc/nodeagentx.ExecuteCommand.EnvEntry
	nil,                       // 20: github.com/cy77cc/nodeagentx.ExecuteScript.EnvEntry
}
var file_proto_agent_proto_depIdxs = []int32{
	3,  // 0: github.com/cy77cc/nodeagentx.AgentMessage.registration:type_name -> github.com/cy77cc/nodeagentx.AgentRegistration
	5,  // 1: github.com/cy77cc/nodeagentx.AgentMessage.heartbeat:type_name -> github.com/cy77cc/nodeagentx.Heartbeat
	6,  // 2: github.com/cy77cc/nodeagentx.AgentMessage.metrics:type_name -> github.com/cy77cc/nodeagentx.MetricBatch
	12, // 3: github.com/cy77cc/nodeagentx.AgentMessage.exec_output:type_name -> github.com/cy77cc/nodeagentx.ExecOutput
	13, // 4: github.com/cy77cc/nodeagentx.AgentMessage.exec_result:type_name -> github.com/cy77cc/nodeagentx.ExecResult
	17, // 5: github.com/cy77cc/nodeagentx.AgentMessage.ack:type_name -> github.com/cy77cc/nodeagentx.Ack
	9,  // 6: github.com/cy77cc/nodeagentx.PlatformMessage.exec_command:type_name -> github.com/cy77cc/nodeagentx.ExecuteCommand
	10, // 7: github.com/cy77cc/nodeagentx.PlatformMessage.exec_script:type_name -> github.com/cy77cc/nodeagentx.ExecuteScript
	15, // 8: github.com/cy77cc/nodeagentx.PlatformMessage.cancel_job:type_name -> github.com/cy77cc/nodeagentx.CancelJob
	16, // 9: github.com/cy77cc/nodeagentx.PlatformMessage.config_update:type_name -> github.com/cy77cc/nodeagentx.ConfigUpdate
	17, // 10: github.com/cy77cc/nodeagentx.PlatformMessage.ack:type_name -> github.com/cy77cc/nodeagentx.Ack
	4,  // 11: github.com/cy77cc/nodeagentx.AgentRegistration.agent_info:type_name -> github.com/cy77cc/nodeagentx.AgentInfo
	4,  // 12: github.com/cy77cc/nodeagentx.Heartbeat.agent_info:type_name -> github.com/cy77cc/nodeagentx.AgentInfo
	7,  // 13: github.com/cy77cc/nodeagentx.MetricBatch.metrics:type_name -> github.com/cy77cc/nodeagentx.Metric
	18, // 14: github.com/cy77cc/nodeagentx.Metric.tags:type_name -> github.com/cy77cc/nodeagentx.Metric.TagsEntry
	8,  // 15: github.com/cy77cc/nodeagentx.Metric.fields:type_name -> github.com/cy77cc/nodeagentx.Field
	0,  // 16: github.com/cy77cc/nodeagentx.Metric.type:type_name -> github.com/cy77cc/nodeagentx.MetricType
	19, // 17: github.com/cy77cc/nodeagentx.ExecuteCommand.env:type_name -> github.com/cy77cc/nodeagentx.ExecuteCommand.EnvEntry
	11, // 18: github.com/cy77cc/nodeagentx.ExecuteCommand.sandbox:type_name -> github.com/cy77cc/nodeagentx.SandboxConfig
	20, // 19: github.com/cy77cc/nodeagentx.ExecuteScript.env:type_name -> github.com/cy77cc/nodeagentx.ExecuteScript.EnvEntry
	11, // 20: github.com/cy77cc/nodeagentx.ExecuteScript.sandbox:type_name -> github.com/cy77cc/nodeagentx.SandboxConfig
	14, // 21: github.com/cy77cc/nodeagentx.ExecResult.stats:type_name -> github.com/cy77cc/nodeagentx.ExecStats
	1,  // 22: github.com/cy77cc/nodeagentx.AgentService.Connect:input_type -> github.com/cy77cc/nodeagentx.AgentMessage
	2,  // 23: github.com/cy77cc/nodeagentx.AgentService.Connect:output_type -> github.com/cy77cc/nodeagentx.PlatformMessage
	23, // [23:24] is the sub-list for method output_type
	22, // [22:23] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	file_proto_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Registration)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Metrics)(nil),
		(*AgentMessage_ExecOutput)(nil),
		(*AgentMessage_ExecResult)(nil),
		(*AgentMessage_Ack)(nil),
	}
	file_proto_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*PlatformMessage_ExecCommand)(nil),
		(*PlatformMessage_ExecScript)(nil),
		(*PlatformMessage_CancelJob)(nil),
		(*PlatformMessage_ConfigUpdate)(nil),
		(*PlatformMessage_Ack)(nil),
	}
	file_proto_agent_proto_msgTypes[7].OneofWrappers = []any{
		(*Field_DoubleValue)(nil),
		(*Field_IntValue)(nil),
		(*Field_StringValue)(nil),
		(*Field_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
